#!/usr/bin/env python3

# We try to stay as close to standard library as possible.
import sys
import json

# Do we have the things we need?
try:
    import argparse
except ModuleNotFoundError:
    print("elastictl requires argparse")
    print("Please run 'pip3 install argparse' before proceeding")
    sys.exit(1)

try:
    import httpx
except ModuleNotFoundError:
    print("elastictl requires httpx")
    print("Please run 'pip3 install httpx' before proceeding")
    sys.exit(1)

# Script specific utilities
# valp has the validate functions
from val_ip import validate_ipv4
# argument parser is generated here
from cli import parser

def main():
    # Build out args object
    args = parser()
    # Are we verbose
    verbose = args.verbose
    # Construct out baseurl from the BaseURL class.
    baseurl = BaseURL(args)
    # Get our color object 
    colors = TextColors()
    # Default action here: simply see if we hit an ES endpoint

    if args.test == True:
        status = EndpointValues(baseurl, verbose, colors).es_up()
        print(status)
    if args.which == "index":
        if args.exists:
            exists_status = EndpointValues(baseurl, verbose, colors).index_exists(args)
            print(exists_status["message"])
            sys.exit(exists_status["exit"])
        elif args.get:
            pass
        elif args.delete:
            pass
        elif args.create:
            pass
    if args.which == "node":
        pass
    if args.which == "cluster":
        pass

# Return a URL object
class BaseURL():
    def __init__(self, args):
        self.protocol = args.protocol
        self.addr = args.addr
        self.port = args.port
        self.baseurl = f"{self.protocol}://{self.addr}:{self.port}"
    def __repr__(self):
        return f"{self.protocol}://{self.addr}:{self.port}"

# Initial entry in to access various endpoints
class EndpointValues():
    def __init__(self, baseurl, verbose, colors):
        self.url = baseurl.baseurl
        self.verbose = verbose
        self.colors = colors
    def cluster(self):
        pass
    # Index related options here.
    def index_exists(self, args):
        try:
            es_status = httpx.get(self.url)
        except:
            return f"{self.colors.FAIL}Error: Unable to connect. Is Elasticsearch running?{self.colors.ENDC}"
        # format our URL
        index_url = f"{self.url}/{ args.name }"
        # Check what our URL request gets
        index_status = httpx.get(index_url)
        # Does the index exist?
        if index_status.status_code == 404:
            message = f"{self.colors.WARN}Error: Index: {args.name} was not found{self.colors.ENDC}"
            status_message =  {"message": message,
                               "exit": 1}
            return status_message
        elif index_status.status_code == 200:
            message = f"{self.colors.OKGREEN}Index: {args.name} exists{self.colors.ENDC}"
            status_message = {"message": message,
                              "exit": 0}
            return status_message
        else:
            message = f"{self.colors.WARN}Error: {index_status.status_code} was received{self.colors.ENDC}"
            status_message = {"message": message,
                              "exit": 1}
            return status_message

    # Simply checks if elasticsearch is running
    def es_up(self):
        try:
            es_status = httpx.get(self.url)
        except:
            return (f"{self.colors.FAIL}Error: Unable to connect. Is Elasticsearch running?{self.colors.ENDC}")

        if es_status.status_code != 200:
            return f"{self.colors.FAIL}Error: Recieved: {es_status.status_code}{self.colors.ENDC}"
        else:
            if self.verbose == True:
                # Get the full data from the endpoint
                return es_status.text
            elif self.verbose == False:
                # We just want to know if the cluster is working.
                es_json = json.loads(es_status.text)
                return f"{self.colors.OKGREEN}Elasticsearch is up! Node: {es_json['name']}{self.colors.ENDC}"

class TextColors():
    def __init__(self):
        self.HEADER = '\033[95m'
        self.OKBLUE = '\033[94m'
        self.OKGREEN = '\033[92m'
        self.WARN = '\033[93m'
        self.FAIL = '\033[91m'
        self.ENDC = '\033[0m'
        self.BOLD = '\033[1m'
        self.UNDERLINE = '\033[4m'

if __name__ == '__main__':
    main()
